import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import NavBar from '@/componenets/NavBar'
import Providers from '@/componenets/Providers'
import { Toaster } from 'sonner'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CarManagys',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <head>
      <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
      </head>
      <body className={cn("relative h-full font-sans antialiased", inter.className)}>
        <main className='relative flex flex-col min-h-screen '>
          <Providers>
          <NavBar/>
            <div
              className='flex-grow flex-1'
            >{children}
            </div>
          </Providers>
        </main> 
        <Toaster position='top-center' richColors/>
      </body>
    </html>
  )
}